### ISSUE TITLE
KNOWN ISSUES

### ISSUE THREAD

**Issue by amotzte** [niral/EFC#16]
כאן יכתבו כל הבאגים אשר קיימים ונו מודעים אליהם אולם עדיין לא פתרנו אותם

**Comment by robi-y** [comment]
כדאי לפתוח כל באג כפריט נפרד - כך יש תיעוד של כל ההתכתבות והפעילות בנושא ואפשר להקצות באגים שונים לאנשים שונים....

**Comment by amotzte** [comment]
אוקיי תודה
בתאריך 2011 12 6 19:52, מאת "robi-y" <
reply@reply.github.com

**Comment by amotzte** [comment]
מה הולך פה זה בכלל לא האתר שלי
